server:
  port: 1007

grpc:
  server:
    port: 9007
  client:
    auth-service:
      address: static://localhost:9001
      negotiationType: plaintext

spring:
  application:
    name: websocket-service

  profiles:
    active: dev
    include: framework

  output:
    ansi:
      enabled: always

  jackson:
    time-zone: Asia/Ho_Chi_Minh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
