server:
  servlet:
    context-path: /files
  port: 1002

spring:
  application:
    name: file

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file_service?authSource=admin

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloudinary:
  url: cloudinary://564311218395733:ucE1Gknj-f02QPlmB0jvd04-N10@dnummyvqk

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info

grpc:
  server:
    enabled: false
  client:
    global:
      enabled: false
