version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_canhtv05
    restart: always
    environment:
      POSTGRES_USER: canhtv05
      POSTGRES_PASSWORD: canhtv05
      POSTGRES_DB: canhtv05
    ports:
      - "5432:5432"
    volumes:
      - postgres_canhtv05:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:latest
    container_name: redis_canhtv05
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_canhtv05:/data

  mongo:
    image: mongo:latest
    container_name: mongo_canhtv05
    environment:
      MONGO_INITDB_ROOT_USERNAME: canhtv05
      MONGO_INITDB_ROOT_PASSWORD: canhtv05
    ports:
      - "27017:27017"
    volumes:
      - mongo_canhtv05:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_canhtv05
    ports:
      - 2000:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: canhtv05
      ME_CONFIG_MONGODB_ADMINPASSWORD: canhtv05
    links:
      - mongo
volumes:
  postgres_canhtv05:
  redis_canhtv05:
  mongo_canhtv05:
