server:
  port: 1000

app:
  api-prefix: /api/v1

spring:
  application:
    name: gateway

  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth
              predicates:
                - Path=${app.api-prefix}/auth/**
              filters:
                - StripPrefix=2

            - id: file-service
              uri: lb://file
              predicates:
                - Path=${app.api-prefix}/files/**
              filters:
                - StripPrefix=2

            - id: profile-service
              uri: lb://user-profile
              predicates:
                - Path=${app.api-prefix}/user-profile/**
              filters:
                - StripPrefix=2

            - id: notification-service
              uri: lb://notification
              predicates:
                - Path=${app.api-prefix}/notifications/**
              filters:
                - StripPrefix=2

            - id: graphql-bff
              uri: lb://graphql-bff
              predicates:
                - Path=${app.api-prefix}/graphql/**
              filters:
                - StripPrefix=3

grpc:
  client:
    auth-service:
      address: static://localhost:9001
      negotiationType: plaintext
    file-service:
      address: static://localhost:9002
      negotiationType: plaintext
    profile-service:
      address: static://localhost:9003
      negotiationType: plaintext
    notification-service:
      address: static://localhost:9004
      negotiationType: plaintext
    graphql-bff:
      address: static://localhost:9006
      negotiationType: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
