application:
  security:
    base64Secret: ${APPLICATION_SECURITY_BASE64SECRET:ASyTTcIvfHA8QsI2c1Fvc8vZUcaeUgRlHH1VhsElDSYHsJ0CS5N0y5/yvKte+WDvYS3lL0oBzPK+1E83ACSdvA==}
    validDurationInSeconds: ${APPLICATION_SECURITY_VALID_DURATION_IN_SECONDS:604800}
    refreshDurationInSeconds: ${APPLICATION_SECURITY_REFRESH_DURATION_IN_SECONDS:1209600}
    cookieDomain: ${APPLICATION_SECURITY_COOKIE_DOMAIN:}
  redis:
    clientName: ${APPLICATION_REDIS_CLIENTNAME:leaf-client}
    address: ${APPLICATION_REDIS_ADDRESS:redis://localhost:6379}
    password: ${APPLICATION_REDIS_PASSWORD:}
    minimumIdle: ${APPLICATION_REDIS_MINIMUM_IDLE:5}
    maxPoolSize: ${APPLICATION_REDIS_MAX_POOL_SIZE:10}
