server:
  port: 1006

grpc:
  server:
    port: 9006
  client:
    profile-service:
      address: static://localhost:9003
      negotiationType: plaintext
    auth-service:
      address: static://localhost:9001
      negotiationType: plaintext
    file-service:
      address: static://localhost:9002
      negotiationType: plaintext

spring:
  application:
    name: graphql-bff

  profiles:
    active: dev
    include: framework

  output:
    ansi:
      enabled: always

  graphql:
    http:
      enabled: true
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations:
        - classpath:graphql/**/*.graphqls

dgs:
  graphql:
    schema-locations: 'classpath*:graphql/**/*.graphqls'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
